# Generated by Django 5.2.4 on 2025-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0003_alter_menucategory_options_menuoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
