# Generated by Django 5.2.4 on 2025-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0005_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstall',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='stall_qrcodes/'),
        ),
    ]
