# Generated by Django 5.2.4 on 2025-07-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0008_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='description',
        ),
    ]
